### ISSUE TITLE
Translate hash to String

### ISSUE THREAD

**Issue by Eragonfr** [RustCrypto/hashes#100]
I'v not found how i can translate the content returned by an sha3 function, can i do that ?

**Comment by tarcieri** [comment]
You need to pick an encoding, and a crate to encode it with. Which encoding you pick depends on your needs. Perhaps [`hex`](https://crates.io/crates/hex)?

**Comment by Eragonfr** [comment]
I don't understand, how i can encode and decode an hash with hex

PS: Oh i need to encode the content returned by the function.
