### ISSUE TITLE
BLAKE3

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/hashes#103]
There is a Rust implementation at: https://github.com/BLAKE3-team/BLAKE3/blob/master/src/

It seems like attempting to have one here would be duplicating efforts.

It has trait impls for  `digest` and  `crypto-mac`.

I think the only actionable thing for this repo is an outbound link in the README.md.

**Comment by DonaldTsang** [comment]
Perhaps use RustCrypto as an API for the pre-existing library?

**Comment by tarcieri** [comment]
@DonaldTsang it already impls the relevant traits from https://github.com/rustcrypto/traits

Aside from linking to it in the README.md, I think we're good to go.

**Comment by DonaldTsang** [comment]
Sounds good
