### ISSUE TITLE
Traits for digests of particular output length

### ISSUE THREAD

**Issue by hdevalence** [RustCrypto/hashes#16]
Currently the `Digest` trait allows writing code that's generic with respect to the choice of hash function. But for an application that requires a certain output size, there's no way to encode that requirement into the type system (e.g., "This function requires a hash function with 512 bits of output").

Perhaps one way to solve this would be to introduce empty `Digest256`, `Digest512`, etc traits, which all inherit the `Digest` trait. Implementing, say, `Digest512` is then a declaration that that hash function has 512 bits of output, so that users can write functions which are generic over hash functions with a fixed output size.

Is this a good idea, or there a better way to do this?

**Comment by newpavlov** [comment]
Output size is associated type in the `Digest` trait, so you can write generic functions over it like this:
```Rust
extern crate digest;
extern crate generic_array;

use digest::Digest;
use generic_array::GenericArray;
use generic_array::typenum::U512;

pub fn digest512<D>(data: &[u8]) -> GenericArray<u8, U512>
                    where D: Digest<OutputSize=U512> + Default {
    let mut state = D::default();
    state.input(data);
    state.result()
}
```

**Comment by hdevalence** [comment]
Oh, awesome! Thanks for explaining this.

**Comment by newpavlov** [comment]
Slowfix: of course you need to use `U64`, not `U512`. Output and block sizes are given as bytes, not bits.
