### ISSUE TITLE
Release shabal v0.3.0?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/hashes#170]
Unfortunately I don't have access to the `shabal` crate, which was merged in #77 

@spebern I see you published `shabal`. Any chance we could get access to it? It's upgraded to `digest` v0.9 and ready to go.

**Comment by spebern** [comment]
I have added you as an owner

**Comment by tarcieri** [comment]
@spebern great, thank you! Mind if I go ahead and publish the crate?

**Comment by spebern** [comment]
No problem, go ahead :-).

**Comment by tarcieri** [comment]
Released in #171
