### ISSUE TITLE
Obtain hash output as a String

### ISSUE THREAD

**Issue by jjpe** [RustCrypto/hashes#185]
Currently, this results in a value of `GenericArray<u8, _>`:

```rust
let input = String::from("hello");

let mut hasher = Sha512::new();
hasher.update(input);
let hash_result = hasher.finalize();
```

However, what I need is not a byte array but a `String` as output.
I tried converting it with `std::str::from_utf8(&hash_result[..])` but that errors out with `Err(Utf8Error { valid_up_to: 0, error_len: Some(1) })` as  an error value. This seems weird to me since the hash should be a hexadecimal string, but that's what I observed. 

How can I get a valid UTF-8 string from `hash_result`?

**Comment by newpavlov** [comment]
First you should select encoding which you want to use for conversion, next use specialized crate to convert byte array to `String`, e.g. [`hex`](https://docs.rs/hex/) or [`base64`](https://docs.rs/base64/).

**Comment by jjpe** [comment]
> First you should select encoding which you want to use for conversion

And how would I do that? I'm not even sure what encoding the bytes are output in, it all depends on `sha2` internals.
I am pretty certain that whatever it is, *the* sane default (i.e. UTF-8) it is not.

**Comment by jjpe** [comment]
nvm, I've figured it out. Thanks for the help :)

**Comment by newpavlov** [comment]
No, it does not depend on `sha2` internals. Hash functions return byte arrays (e.g. for SHA-512, it's 64 bytes), which can be converted to string in different ways and this "[binay-to-text encoding](https://en.wikipedia.org/wiki/Binary-to-text_encoding)" is orthogonal to "string encoding" such as UTF-8. My guess is that you probably want to use the `hex` crate.

**Comment by legendofmiracles** [comment]
How can i specify the return encodation? @jjpe

**Comment by tarcieri** [comment]
As @newpavlov mentioned above, you need to pick a crate that implements your desired encoding, like `hex` or `base64`, then use that to encode the binary output.

**Comment by legendofmiracles** [comment]
Thanks for the swift response!
I have chosen the hex crate, and i am also trying to decode the string with it. 
But it returns this:
```
[138, 7, 202, 14, 106, 100, 159, 68, 41, 185, 130, 103, 177, 235, 243, 183, 156, 44, 168, 87, 171, 182, 13, 145, 224, 129, 24, 166, 27, 29, 158, 107, 207, 24, 64, 222, 142, 3, 128, 57, 42, 9, 195, 55, 102, 218, 247, 20, 99, 178, 23, 148, 231, 238, 37, 150, 105, 11, 30, 41, 201, 95, 119, 196]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexCharacter { c: '\u{8a}', index: 0 }', src/hash.rs:61:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
And this leads me, to believe that the data i get isn't encoded in hex, thus the question, how can i specify to return it in hex.

**Comment by legendofmiracles** [comment]
or wait, i have to encode the output?
and then decode it again??
(sorry for me asking so stupid, i have no idea of crypto stuff)

**Comment by tarcieri** [comment]
Yes

**Comment by legendofmiracles** [comment]
Sorry to ask again, but now i am encoding the input of the user into a hash, then i am encoding it to hex, and then decoding it, back to byes. but when i *then* want to decode it into a string, with the `std::str::from_utf8` method, it always returns the error, seen above. The decoding to/from hex works perfectly fine tho. Also, the error comes regardless of input. @tarcieri

**Comment by newpavlov** [comment]
> when i then want to decode it into a string, with the std::str::from_utf8 method

When you decode hash bytes from hex you get arbitrary bytes, which almost never are valid UTF-8, either use `hex::encode` again or transform hex-encoded value to bytes via the [`as_bytes()`](https://doc.rust-lang.org/std/primitive.str.html#method.as_bytes) method.

P.S.: A better place for such questions with a much wider audience which could help is [URLO](http://https://users.rust-lang.org).

**Comment by erayerdin** [comment]
Strangely, I have different results for hash I get from e.g. [here](https://emn178.github.io/online-tools/sha256.html) and from `hex::encode`. 

I implemented an extension trait as such:

```rust
trait FileHashExt {
    fn sha256(&mut self) -> Result<String, OperationError>;
}

impl FileHashExt for File {
    fn sha256(&mut self) -> Result<String, OperationError> {
        debug!("Generating SHA256 hash for file...");

        let mut hasher = Sha256::new();

        let mut buffer = [0u8; 8];
        loop {
            match self.read(&mut buffer) {
                Ok(bytes_read) => {
                    if bytes_read == 0 {
                        break;
                    } else {
                        hasher.update(buffer);
                    }
                }
                Err(e) => {
                    return Err(OperationError::new(
                        CommonExitCodes::StdIoError as i32,
                        "An error occured while reading file to generate hash.",
                        Some(e),
                    ))
                }
            }
        }
        let hash = hasher.finalize().to_vec();

        Ok(hex::encode(hash))
    }
}
```

Does anyone have any idea?

**Comment by newpavlov** [comment]
@erayerdin 
You code is incorrect. You should replace `hasher.update(buffer);` with `hasher.update(buffer[..bytes_read]);`. You could significantly simplify your code by using implementation of `io::Write` for `Sha256` and [`io::copy`](https://doc.rust-lang.org/std/io/fn.copy.html). Also note that `to_vec` is unnecessary.

**Comment by nik-rev** [comment]
Here is how to get sha256 output as a string:

```rust
pub(crate) fn sha256_digest(bytes: &[u8]) -> String {
    format!("sha256:{}", hex::encode(sha2::Sha256::digest(bytes)))
}
```

You need the `hex` crate.

**Comment by newpavlov** [comment]
We recommend to use the [`base16ct`](https://docs.rs/base16ct) crate instead of `hex`.
