### ISSUE TITLE
Add a general usage introduction to the README

### ISSUE THREAD

**Issue by hgrecco** [RustCrypto/hashes#19]
One of the nice thing of a project like this is that all crates share a common API. It would be nice to describe such API in the project README (and list exceptions, if any)

**Comment by newpavlov** [comment]
Thank you for you input!

I will update the readme and the `crypto-hashes` documentation with a proper API description in the following days.

**Comment by newpavlov** [comment]
I've added a usage section to the README, if you have any additions or comments I will be happy to hear them!

**Comment by hgrecco** [comment]
Thanks!
