### ISSUE TITLE
MD5 Documentation link refers to wrong crate

### ISSUE THREAD

**Issue by Dr-Emann** [RustCrypto/hashes#21]
The md5 [documentation link](https://github.com/RustCrypto/hashes/blob/0ab2d59c47c5ecb2c4d36899f822dfb7f3dd9aad/md5/Cargo.toml#L7) links to the md5 crate instead of the md-5 crate documentation

**Comment by newpavlov** [comment]
Thank you for noticing this!

Fixed it and added link to docs for the `sha-1` crate.
