### ISSUE TITLE
Missing tags and commits for sha2-0.9.2

### ISSUE THREAD

**Issue by dignifiedquire** [RustCrypto/hashes#218]
The latest release on crates.io is 0.9.2, but there seems to be no tag, nor commit message pointing at which git version this is.

**Comment by tarcieri** [comment]
It looks like it was released at or around 13e226a83a66f6cc330e453d58954c1c267a7f99

**Comment by newpavlov** [comment]
Thank you for noticing! Fixed: https://github.com/RustCrypto/hashes/tree/sha2-v0.9.2
