### ISSUE TITLE
blake2: expose round function for Argon2

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/hashes#223]
The `argon2` crate presently vendors an implementation of the BLAKE2 round function:

https://github.com/RustCrypto/password-hashes/issues/105

It'd be nice if it could source this functionality from the `blake2` crate, particularly if it ever adds e.g. SIMD functionality

**Comment by HeCorr** [comment]
This should probably be closed since https://github.com/RustCrypto/password-hashes/issues/105 itself has been closed?
