### ISSUE TITLE
Expose sha1::compress publicly?

### ISSUE THREAD

**Issue by not-an-aardvark** [RustCrypto/hashes#237]
I'm trying to accomplish the following task on [this project](https://github.com/not-an-aardvark/lucky-commit):

1. Using the `sha-1` crate, run sha1 on a few blocks of data, once, without finalizing.
2. Save the sha1 state vector from step (1)
3. Run a different implementation of sha1 (e.g. within a GPU) on a small number of remaining blocks, using the state vector from (2) as an initial state.

This is a bit difficult to do with the `sha-1` library. Since a `Sha1` struct doesn't expose its internal state (the `h` field), it's not possible to copy the state from step 2 and use it elsewhere. Additionally, since the `Sha1` struct is the only entrypoint to the crate, I also can't use `sha1::compress` to keep track of state while buffering the data manually. My current workaround is to depend on the `sha1-asm` crate, which [does expose the `compress` API I need](https://docs.rs/sha1-asm/0.5.0/sha1_asm/fn.compress.html). But this isn't ideal, because I lose support for the `sha-1` crate's implementation that uses SHA1 intrinsics, as well as its software implementation of `compress` for architectures that don't support the assembly version.

Admittedly, this is a very unusual use case, so it would be understandable if the answer is to just fork the repo. But since `sha1::compress` is a fairly well-established primitive and is already implemented, I thought I would ask it you'd be open to making it accessible from outside the crate.

**Comment by tarcieri** [comment]
It's fine. We have a `compress` feature in the `sha2` crate for similar reasons:

https://github.com/RustCrypto/hashes/blob/c5fbbc5/sha2/src/lib.rs#L70-L71

**Comment by newpavlov** [comment]
Yes, exposing the compression function like we did in `sha2` should be simple enough. Also note that in `digest v0.10` we will expose [block-level APIs](https://docs.rs/digest/0.10.0-pre.3/digest/core_api/index.html) (you probably will be most interested in the `UpdateCore` trait), together with additional inherent getters for retrieving hasher state I think should cover your use-case.

**Comment by not-an-aardvark** [comment]
Thanks!
