### ISSUE TITLE
reexport ArrayLength or maybe generic_array?

### ISSUE THREAD

**Issue by lattice0** [RustCrypto/hashes#255]
To do this:

```
use sha2::{Sha256, Digest};
use std::ops::Add;
use digest::generic_array::ArrayLength;

fn hash_password<Hash: Digest>(password: &str, salt: &str, output: &mut [u8]) 
    where <Hash as Digest>::OutputSize: Add, <<Hash as Digest>::OutputSize as Add>::Output: ArrayLength<u8> {
    format!("{:x}",<sha2::Sha256>::digest(format!("{}:{}", "", "").as_bytes()));
}

fn main() {
    let mut buf2 = [0u8; 32];
    hash_password::<Sha256>("my_password", "abcd", &mut buf2);
}
```

I had to import the `digest` crate, as `sha2` does not reexport `generic_array` or simply `ArrayLength`. It's usefulf to reuse the digest trait for lots of functions. Shouldn't we reexport at least `ArrayLength` or maybe `generic_array` entirely? I can make the PR if needed.

I'm on a situation where I want to call the `digest` based on a generic type that implements it. I don't see why I should add `digest` on my Cargo just for that.

**Comment by newpavlov** [comment]
`sha2` and all other crates in this repository re-export `digest`, so you can import `ArrayLength` as `use sha2::digest::generic_array::ArrayLength`.
