### ISSUE TITLE
Compilation error when used as a dependency

### ISSUE THREAD

**Issue by sbp** [RustCrypto/hashes#26]
When trying to install `tectonic` which depends on this:

```
error: `Self` and associated types in struct expressions and patterns are unstable (see issue #37544)
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/md-5-0.4.3/src/lib.rs:40:9
   |
40 |         Self {
   |         ^^^^
```

Though, strangely, the Travis CI build is passing.

**Comment by newpavlov** [comment]
You are using the older version of Rust. (Travis CI tests only for current stable) I will update code so it will be compatible with the older versions of Rust. (should be at least 1.13)

I also probably should determine minimal Rust version for the crates and add relevant tests to Travis CI.

**Comment by sbp** [comment]
Thanks for the extremely quick response. For reference I was on `rustc 1.15.1` and `cargo 0.16.0-dev`. I'd installed them just before building `tectonic`, but it turned out that my homebrew installation was corrupt and wasn't updating properly!

**Comment by newpavlov** [comment]
I've replaced `Self`, so now you can either update `md-5` to 0.4.4 or Rust to 1.16. :)
