### ISSUE TITLE
VariableOutput implementation is incorrect for BLAKE2

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/hashes#28]
As was [noticed](https://github.com/RustCrypto/hashes/pull/17#issuecomment-308660800) by @Ralith `VariableOutput` is currently incorrectly implemented for BLAKE2, as output size must be included in the parameters block.

**Comment by tailhook** [comment]
Any updates? This is a severe bug that produces incorrect hash values, and presumably also requires breaking changes to the API.

**Comment by newpavlov** [comment]
`blake2` code needs a bit of cleanup and `digest` traits will need a small rework. Unfortunately last month I couldn't allocate enough time to work on it. For now I think I will simply remove `VariableOutput` implementation for `blake2` and will yank `v0.6.0`.

**Comment by newpavlov** [comment]
I've fixed `VariableOutput` implementation in v0.7. Now it produces the same results as pre-rework implementation.
