### ISSUE TITLE
why do the hashes derive copy

### ISSUE THREAD

**Issue by cardoe** [RustCrypto/hashes#30]
So this is something I'm hoping can be documented somewhere. I'm curious why the hashes derive copy because it seems like not the behavior you'd want. If you accidentally forget to pass your data by reference you will get an automatic copy which is not something you'd likely want in this case. Typically I've found if the `impl` has `mut` on self then you don't want copy.

e.g.

```
enum Foo {
   Sha(sha2::Sha256),
   Md5(md5::Md5),
}

struct Bar {
  hash: Foo,
}

impl Bar { 
  fn some_data(&mut self, data: &[u8]) {
    match self.hash {
      Foo::Sha(mut hash) => hash.input(data),
      Foo::Md5(mut hash) => hash.input(data),
   }
  }
}
```

What's the expected behavior here?

**Comment by newpavlov** [comment]
Initially I wasn't sure if `Copy` should be implemented, but I though that in some rare cases it will be unnecessary restrictive. But I forgot about potential surprises like in your example. Indeed implementing only `Clone` should be more than enough.

I will remove `Copy` impl in the next version.

**Comment by newpavlov** [comment]
I've updated hashes to version 0.7. Now none of them should implement `Copy`.
