### ISSUE TITLE
how get middle value data for sm3 instance

### ISSUE THREAD

**Issue by weihualiu** [RustCrypto/hashes#304]
I want to get a SM3 instance's data to binary data.
example:
```rust
    let mut hasher = Sm3::new();
    let result1: Vec<u8> = hasher.to_vec();
    // update
   hasher.update(b"hello world");
    let result2: Vec<u8> = haser.to_vec();
   // result1 vs result2 is not same. because result2 is execute update function operation.

```

What I use or write code?

**Comment by newpavlov** [comment]
I am not sure I fully understand your request. Do you want to serialize hasher stare and send it to a separate computer? If so, then currently it's not possible to do and we do not plan to add such functionality.

If you simply want to get hash values of two messages with a same prefix (e.g. for `foobar` and `foobar1234`) without hashing  the prefix twice, then you can clone the hasher state:
```rust
use sm3::{Sm3, Digest};

let mut hasher = Sm3::new();
hasher.update("foobar");
// note the clonining
let hash1 = hasher.clone().finalize();
hasher.update("123");
// returns hash for "foobar123"
let hash2 = hasher.finalize();
```

**Comment by weihualiu** [comment]
Yet, I want to serialize hasher stare and send it to a separate computer.

**Comment by newpavlov** [comment]
What is your use case? In general we are really conservative about implementing (de)serialization traits on cryptographic primitives. Not only it constrains us from changing inner structure, which may be useful for performance improvements, but also may result in exposure of sensitive data, e.g. hash functions process data in blocks, so state serialization would require inclusion of unprocessed part of the input message.

**Comment by newpavlov** [comment]
Going to close this issue for now as wontfix. I will open a separate issue for discussion on potential implementation of `serde` traits for hash functions.
