### ISSUE TITLE
How to store(cache) sha256 hash value?

### ISSUE THREAD

**Issue by johalun** [RustCrypto/hashes#309]
I want to store the hash in a struct and I'm having trouble with this.. It says return type of digest() is GenericArray<u8, U64> but I can't find the U64 type anywhere.

Help appreciated.

**Comment by newpavlov** [comment]
It comes from the [`typenum`](https://docs.rs/typenum/) crate. You can access it without explicitly adding to your dependencies as `sha2::digest::generic_array::typenum`. Also the typenum "constants" are re-exported as [`sha2::digest::consts`](https://docs.rs/digest/0.9.0/digest/consts/index.html).

Probably a simpler solution for you would be to convert `GenericArray<u8, U64>` to `[u8; 64]` via the [`Tryinto`](https://doc.rust-lang.org/core/convert/trait.TryInto.html) trait (you can simply `unwrap` or `expect` the conversion error, compiler will remove this panic).

**Comment by johalun** [comment]
I'm having trouble both with the type and conversion. It doesn't implement try_into.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2ddb5d0c8047543361abbc83ec02cec6

```
 --> src/main.rs:7:39
  |
7 |     let hash: GenericArray<u8, U64> = sha2::Sha256::digest("Hello".as_bytes());
  |               ---------------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `UInt`, found struct `UTerm`
  |               |
  |               expected due to this
  |
  = note: expected struct `GenericArray<_, UInt<UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, _>, _>, _>, _>, _>>`
             found struct `GenericArray<_, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, _>, _>, _>, _>, _>>`
```

**Comment by newpavlov** [comment]
`Sha256` returns 32 bytes, not 64, i.e. you should use `GenericArray<u8, U32>`. The `TryInto` part was about conversion to arrays: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bf9d7c329195b644e1504dd7ffe93944.

**Comment by johalun** [comment]
Oh yeah, you're right about that. Now it works better :)  Don't know where i got U64 from...  Thanks!

**Comment by johalun** [comment]
try_into() worked correctly once I got the type correct.
