### ISSUE TITLE
Disable ASM hashes on MSVC?

### ISSUE THREAD

**Issue by not-an-aardvark** [RustCrypto/hashes#315]
As documented in https://github.com/RustCrypto/asm-hashes/issues/17 and elsewhere, the crates in `asm-hashes` don't work on Windows MSVC targets. This is unfortunate, but it's understandable given that assembly is inherently difficult to port to all platforms.

However, it seems unnecessary that this detail leaks into the crates in the `hashes` repository. Would it make sense to use conditional compilation to force the software versions of hashes on MSVC, even when the `asm` feature is enabled? (There is [already precedent](https://github.com/RustCrypto/hashes/blob/726e3c3978a77eb4318b4511eed5ac885375acd0/sha1/src/compress.rs#L23-L26) for ignoring the `asm` feature flag when no assembly builds are available for the current platform.)

My use case is that I want to enable the `asm` feature to allow for faster performance on compatible platforms, but I don't want to completely break the build for Windows users. I'd be happy to create a PR if you think this is a reasonable change.

**Comment by newpavlov** [comment]
Sounds reasonable. But I wonder whether we should use black- or white-list approach here (i.e. disable for MSVC or enable for GNU and other supported toolchains).

**Comment by newpavlov** [comment]
Dependency on asm-hashes will be removed in v0.11 releases.

**Comment by tarcieri** [comment]
@newpavlov should we close the remaining issues on https://github.com/RustCrypto/asm-hashes and archive it?

**Comment by newpavlov** [comment]
Yes, but I think we should do it after v0.11 hashes are released.
