### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by guidovranken** [RustCrypto/hashes#326]
# OSS-Fuzz

[OSS-Fuzz](https://github.com/google/oss-fuzz) is an initiative by Google which continually fuzzes open source software on Google infra, free of charge.

# Fuzzer

For fuzzing cryptographic libraries I use [Cryptofuzz](https://github.com/guidovranken/cryptofuzz) which uses differential fuzzing to find implementation bugs. It has found [hundreds of bugs](https://github.com/guidovranken/cryptofuzz#bugs-found-by-cryptofuzz) in major libraries.

Currently implemented for RustCrypto: most hashes + HMAC with most hashes + CMAC/aes + most KDFs + OFB/CFB/CTR with most block ciphers encryption/decryption + bignum ops (U256).

I will be extending the harness going forward.

# What I need

One or more e-mail addresses of the maintainers linked to a Google account. These will be publicly viewable in the `project.yaml` file of the OSS-Fuzz project.

# What is expected from you

OSS-Fuzz will send automated reports upon discovering a bug. It is expected that you fix the bug. I will be stand by to explain the fuzzer output and create a reproducer if needed. OSS-Fuzz will automatically detect if a bug has been fixed. The bug will be publicly disclosed after 90 days, regardless of whether it has been fixed or not.

Please let me know if there is any interest in this.

**Comment by newpavlov** [comment]
Sounds great! You can use my email (newpavlov@gmail.com), @tarcieri also may be interested.

Note that we plan to [migrate](https://github.com/RustCrypto/hashes/pull/217) crate to `digest v0.10`, so you may want to wait until the updates get released.

**Comment by guidovranken** [comment]
Great, thanks for your quick reply. I will do the integration now and once you merge that PR I will fix any build failures. @tarcieri 's e-mail can be added later.

**Comment by tarcieri** [comment]
@guidovranken you can add me at bascule@gmail.com

**Comment by guidovranken** [comment]
Thanks. The project has been integrated. If a bug is found you will get an e-mail. In the e-mail is a link to the bug report; you can click it and log in with your Google account. We can comment on the bug report; I will provide bug and reproduction information for you there. You will also receive an e-mail whenever a bug is detected as being fixed. Please feel free to reach out to me if you have any questions.
