### ISSUE TITLE
digest_reader incorrect behaviour on short read 

### ISSUE THREAD

**Issue by aep** [RustCrypto/hashes#33]
in digest/src/digest.rs line 72

    if bytes_read != buffer.len() {

that will terminate on short read, which breaks with asynchronous Read, which may not have the full buffer at the current time, but will have more later.
it should terminate when bytes_read == 0 instead (EOF)

see https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read

**Comment by newpavlov** [comment]
Thank you for noticing this! I will publish update immediately.
