### ISSUE TITLE
Getting `the parameter type 'OutSize' may not live long enough` when upgrading from `blake2` `0.9 -> 0.10`

### ISSUE THREAD

**Issue by HCastano** [RustCrypto/hashes#333]
Hey 👋 

We're using the `blake2` crate in the [`ink!` project](https://github.com/paritytech/ink), and recently [Dependabot tried to upgrade us from `v0.9` to `v0.10`](https://github.com/paritytech/ink/pull/1072). However, we're running into the following error message:

```
    Checking blake2 v0.10.0
error[E0310]: the parameter type `OutSize` may not live long enough
   --> /home/hernando/.cargo/registry/src/github.com-1ecc6299db9ec823/blake2-0.10.0/src/macros.rs:364:13
    |
364 |             type OutputSize = OutSize;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /home/hernando/.cargo/registry/src/github.com-1ecc6299db9ec823/blake2-0.10.0/src/lib.rs:143:1
    |
143 | blake2_mac_impl!(Blake2bMac, Blake2bVarCore, U64, "Blake2b MAC function");
    | ------------------------------------------------------------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound `OutSize: 'static`...
    = note: ...so that the type `OutSize` will meet its required lifetime bounds...
note: ...that is required by this bound
   --> /home/hernando/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-common-0.1.0/src/lib.rs:46:40
    |
46  |     type OutputSize: ArrayLength<u8> + 'static;
    |                                        ^^^^^^^
    = note: this error originates in the macro `blake2_mac_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0310]: the parameter type `OutSize` may not live long enough
   --> /home/hernando/.cargo/registry/src/github.com-1ecc6299db9ec823/blake2-0.10.0/src/macros.rs:364:13
    |
364 |             type OutputSize = OutSize;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /home/hernando/.cargo/registry/src/github.com-1ecc6299db9ec823/blake2-0.10.0/src/lib.rs:173:1
    |
173 | blake2_mac_impl!(Blake2sMac, Blake2sVarCore, U32, "Blake2s MAC function");
    | ------------------------------------------------------------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound `OutSize: 'static`...
    = note: ...so that the type `OutSize` will meet its required lifetime bounds...
note: ...that is required by this bound
   --> /home/hernando/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-common-0.1.0/src/lib.rs:46:40
    |
46  |     type OutputSize: ArrayLength<u8> + 'static;
    |                                        ^^^^^^^
    = note: this error originates in the macro `blake2_mac_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0310`.
```

To reproduce you can clone Dependabot's branch and simply run `cargo check`. 

I'm running on Ubuntu 20.04 Focal with the following compiler versions:
```
❯ rustc +stable --version
rustc 1.57.0 (f1edd0429 2021-11-29)
❯ rustc +nightly --version
rustc 1.59.0-nightly (efec54529 2021-12-04)
```

Thanks!

**Comment by newpavlov** [comment]
Have you seen the crate's [changelog](https://github.com/RustCrypto/hashes/blob/master/blake2/CHANGELOG.md#0100-2021-12-07)? The error is somewhat weird and I'll try to reproduce it later, but you certainly haven't properly migrated to `blake2` v0.10.

**Comment by bk138** [comment]
Having the same error with a newly incorporated argon2 v0.3.2 dependency.

**Comment by newpavlov** [comment]
@bk138 
Can you show a code snippet which reproduces this issue?

**Comment by bk138** [comment]
> @bk138 Can you show a code snippet which reproduces this issue?

Yep! Just found out it seems to be related to the edition in use: here's a Cargo.toml that shows the issue:
```
[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
argon2 = "0.3"
rand_core = { version = "0.6", features = ["std"] }
```
The issue goes away if the edition is changed to 2021.

**Comment by bk138** [comment]
> @bk138 Can you show a code snippet which reproduces this issue?

Yep, here's a minimal repo that exposes the issue: https://github.com/bk138/blake2err

Note that after running `cargo update` which updates the libc and typenum crates, the error goes away.

PS: after only updating typenum from 1.13.0 to 1.14.0, the issue is gone, so this might as well be the fix.

**Comment by HCastano** [comment]
I just updated `typenum` from `v1.13.0 -> v1.14.0` and this fixes the issue. Thanks @bk138!

**Comment by newpavlov** [comment]
Hm, interesting. We probably should release a patch release of `crypto-common` which would pin `typenum` to ^1.14. I guess this issue is a good motivation for resolving RustCrypto/traits#162.
