### ISSUE TITLE
Cannot get the sha1 example to compile

### ISSUE THREAD

**Issue by midnightcodr** [RustCrypto/hashes#334]
Taking the codes from the sha1 example,
```rust
use hex_literal::hex;
use sha1::{Digest, Sha1};

fn main() {
    // create a Sha1 object
    let mut hasher = Sha1::new();

    // process input message
    hasher.update(b"hello world");

    // acquire hash digest in the form of GenericArray,
    // which in this case is equivalent to [u8; 20]
    let result = hasher.finalize();
    assert_eq!(result[..], hex!("2aae6c35c94fcfb415dbe95f408b9ce91ee846ed"));
}
```

The program won't even compile, got the following error:
```
error[E0599]: no method named `finalize` found for struct `Sha1` in the current scope
  --> src/main.rs:13:25
   |
13 |     let result = hasher.finalize();
   |                         ^^^^^^^^ method not found in `Sha1`
```

Is the doc outdated?

**Comment by newpavlov** [comment]
Are you using the `sha-1` crate? [Note](https://github.com/RustCrypto/hashes#crate-names) that the `sha1` crate is not part of our project. The doctests are tested as part of our CI, so they are not outdated.

I was not able to reproduce your issue with the following `Cargo.toml`:
```toml
[dependencies]
sha-1 = "0.10"
hex-literal = "0.3"
```

**Comment by midnightcodr** [comment]
You are right @newpavlov I wasn't using `sha-1` crate. Switching to it solved the issue. Thanks!
