### ISSUE TITLE
0.10.0 and 0.10.1 fails to compile

### ISSUE THREAD

**Issue by VersBinarii** [RustCrypto/hashes#348]
Hello,

Those two versions of blake2 hash  fail to compile with following error:

```
error[E0310]: the parameter type `OutSize` may not live long enough
   --> /home/kris/Devel/hashes/blake2/src/macros.rs:364:13
    |
364 |             type OutputSize = OutSize;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /home/kris/Devel/hashes/blake2/src/lib.rs:143:1
    |
143 | blake2_mac_impl!(Blake2bMac, Blake2bVarCore, U64, "Blake2b MAC function");
```

I created a pull request #347 to add those bounds in

**Comment by newpavlov** [comment]
Weird... I can not reproduce it. What compiler version are you using? Have you tried `cargo update`?

**Comment by VersBinarii** [comment]
I'm using:
```
➜ rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

And just to clarify it, i see this error when compiling my app that is using the blake crate not when compiling the blake crate directly.
Hope that makes sense as i was confused by this as well.

**Comment by newpavlov** [comment]
I was unable to reproduce it in a separate app as well. I guess, I will simply merge your PR for now, since it should not have any negative impact.
