### ISSUE TITLE
Please add more inline examples in the documentation.

### ISSUE THREAD

**Issue by dpc** [RustCrypto/hashes#35]
I'm trying to figure out how to get a digest of a given size, and there is so many abstraction and crates involved, and the source is based on macros, obfuscating what is going on, that it's beyond me at this late hour.

I realize it's a lot of work, and don't want to just complain. I'm just trying to point out the issue. All these efforts are greatly appreciated!

**Comment by newpavlov** [comment]
I am always interested to hear from new users about difficulties which they experience trying to use RustCrypto crates, so you are certainly welcomed!

Could you please specify your use case? Are you interested in one particular algorithm? Have you read [readme](https://github.com/RustCrypto/hashes#usage) and did you find something unclear or difficult to understand? Or do you want to see additional explanations regarding trait usage in the crates documentation?

**Comment by dpc** [comment]
My specific issue is: I need a digest of a given size. I was under impression that blake2 can support that and there is some generics-magic that allows doing it directly in the library, but I wasn't able to figure out how to use it. For now I've settled on manually copying subslice:

https://github.com/dpc/rdedup/blob/cd57e5a54c7aa6ee44dd6cf49ecceb4038314bd5/lib/src/hashing.rs#L59

I am planning to optimize and rework it at some point.

But generally, my point is: it's best if the structs, methods etc. are not only described "Does this and that", but also contain code samples on how to use them, etc. The fact that eg. `blake2b` implements multiple traits, and the meaning of `input` changed between 0.5 to 0.6 confused me a lot (in sha256).

**Comment by newpavlov** [comment]
I've added some [docs](https://docs.rs/blake2/0.7.0/blake2/) to `blake2` crate. Now it includes section which describes how to acquire variable output size. Unfortunately it's a bit difficult to add docs directly to `Blake2b` and `Blake2s` due to the fact that they defined using macro.

Do you think it's enough for new user to start with the `blake2` or should docs be more detailed?

Do you think it's worth to add inline examples to trait methods as well?

**Comment by newpavlov** [comment]
I've added examples to all crates and link to the readme. I think it should be enough for now. But feel free to open additional issues and PRs!
