### ISSUE TITLE
Libraries which use `constant_time_eq` are not `no_std`

### ISSUE THREAD

**Issue by Pratyush** [RustCrypto/hashes#36]
Hi,

Any library which uses the `constant_time_eq` crate is not `no_std`. The [source](https://github.com/cesarb/constant_time_eq/blob/master/src/lib.rs) does not have a `#![no_std]` annotation.

**Comment by newpavlov** [comment]
Thank you for noticing this!

Quite unfortunately Rust does not [automatically detect](https://github.com/rust-lang/rust/issues/38509) such kind of oversights. If @cesarb will not accept your PR in the following days, I'll make a change to `crypto-mac` crate. For now you could try to use [`[replace]`](http://doc.crates.io/manifest.html#the-replace-section) section in your `Cargo.toml` to override `constant_time_eq` to your modified version.

**Comment by Pratyush** [comment]
I agree, figuring out which dependency is pulling in `std` is currently a rather cumbersome process. Hopefully @cesarb will accept the PR quickly!

In the meanwhile, I use [this `serde` test](https://github.com/serde-rs/serde/tree/master/test_suite/no_std) for checking if a crate is truly `no_std`. Perhaps you can add this to your test suite and/or CI?

EDIT: I notice you mentioned changing `crypto-mac`, but `blake2` also uses `constant_time_eq`. It's what I was using.

**Comment by newpavlov** [comment]
`blake2` [does not use](https://github.com/RustCrypto/hashes/blob/master/blake2/Cargo.toml) `constant_time_eq` directly, but through [`crypto-mac`](https://github.com/RustCrypto/traits/blob/master/crypto-mac/Cargo.toml) crate.

As for tests, as I understand `serde` test works only on nightly, so to add this test we'll need to use a bit more complex `.travis.yml` than we have now. For now I will create an issue for that.

**Comment by Pratyush** [comment]
Oops, you're completely right. For some reason I thought that blake2 used `constant_time_eq` directly.

**Comment by Pratyush** [comment]
@cesarb published version `0.1.3` of `constant_time_eq` that is `no_std`.

**Comment by newpavlov** [comment]
Great! Does `cargo update` fix your issue?

**Comment by Pratyush** [comment]
Yup, seems to be working now!
