### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/hashes#37]
- [x] Add crate specific feature tests (including `asm`)
- [x] Add big-endian tests (using either qemu or https://github.com/japaric/trust.) [#40]
- [x] Test minimal Rust versions for crates (currently all crates support 1.13 or higher)
- [x] Add tests to check if crates are truly `no_std` (see #36)

**Comment by newpavlov** [comment]
The oldest Rust version which is continuously tested will be 1.18 to simplify CI config by using only `test --all`

**Comment by quininer** [comment]
We can use [utest](https://github.com/japaric/utest) to do `no-std` test. (thanks @japaric !!)

~~`digest` can not currently be build because `generic-array` specifies a [`typenum` with std](https://github.com/fizyk20/generic-array/blob/master/Cargo.toml#L15).~~

```
$ xargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling byte-tools v0.2.0
   Compiling arrayref v0.3.4
   Compiling typenum v1.9.0
error[E0463]: can't find crate for `std`

error: aborting due to previous error

error: Could not compile `typenum`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by newpavlov** [comment]
`typenum` always [enables](https://github.com/paholg/typenum/blob/master/src/lib.rs#L46) `#![no_std]`. Problem originates from `typenum` building process which [requires](https://github.com/paholg/typenum/blob/8ff62fafe1a8127638a307d5ead80ec1bf9794c0/build/main.rs) `std`. I think xargo should be able to handle such cases correctly.

**Comment by quininer** [comment]
You are right.

**Comment by japaric** [comment]
@quininer Try with `xargo build --target x86_64-unknown-linux-gnu`. `xargo build` will build the build scripts against the Xargo sysroot, which doesn't have std.

**Comment by newpavlov** [comment]
I've added `xargo build` to CI config, I think it should be enough to catch slipped `std` in future. Thank you @japaric!
