### ISSUE TITLE
Sha256 (and seemingly most others) do not implement Debug

### ISSUE THREAD

**Issue by shepmaster** [RustCrypto/hashes#38]
This makes it *really* painful to include one of these types into my own struct as now I have to implement `Debug` by hand. If the internals are being hidden for some reason, could the library provide an implementation that prints something like `Sha256 { ... }`?

**Comment by newpavlov** [comment]
Sorry for late reply! In version 0.7 of crates all hashes now use opaque `Debug` implementation (i.e. `HasherName { ... }`). Plus tests from `digest` crate now require that tested hash function implements `Debug`.
