### ISSUE TITLE
Supporting FNV1a hashing.

### ISSUE THREAD

**Issue by HindrikStegenga** [RustCrypto/hashes#380]
Hello there,

I'm the author of the [`const-fnv1a`](https://crates.io/crates/const-fnv1a-hash) crate and, before putting in any efforts toward it, was wondering if perhaps you'd be interested in adding the FNV1a code to this project? 

Kind regards,

**Comment by tarcieri** [comment]
As FNV is a non-cryptographic hash function, I'm not sure it makes sense for it to be located here.

Thanks for the offer, though!
