### ISSUE TITLE
How can I update the digest and md4 crates in this repository?

### ISSUE THREAD

**Issue by ghost** [RustCrypto/hashes#383]
I'm getting many errors when I update the digest and md4 crates from `"0.9"` to `"0.10.3"` and `"0.10.1"` in [this repository](https://github.com/runfalk/ed2k-rs), how can I fix them?
```
type OutputSize not a member of trait `FixedOutput`
OutputSizeUser is not satisfied
the trait `OutputSizeUser` is not implemented for `Ed2kHasher`
```

**Comment by ghost** [comment]
fixed

**Comment by newpavlov** [comment]
I am not sure you should implement the `digest` traits for the ed2k hashing algorithm. IIRC it's closer to Merkle tree hashing. Also note that you don't have to keep both `md4` and `digest` in your Cargo.toml, since the former [re-exports](https://docs.rs/md4/latest/md4/#reexports) the latter.
