### ISSUE TITLE
integrate projects like clap-digest?

### ISSUE THREAD

**Issue by wookietreiber** [RustCrypto/hashes#391]
I have just released a project that integrates the RustCrypto digests/hashes with [clap](https://crates.io/crates/clap) in the form of a [`ValueEnum`](https://docs.rs/clap/3.2.17/clap/trait.ValueEnum.html) for easy use in clap CLI definitions. This is an effort to make https://github.com/RustCrypto/hashes/pull/390 even more convenient for clap users. For more information on clap-digest, see https://crates.io/crates/clap-digest. 

Given the RustCrypto organization here, I was wondering if you'd like to integrate a project like this into the organization? What is your opinion on that? Are there guidelines, standards, etc.?

**Comment by tarcieri** [comment]
I think it would make more sense to make that part of the `clap` project rather than @RustCrypto.

We largely focus on implementations of cryptographic algorithms/primitives and cryptography-related encoding formats.

**Comment by wookietreiber** [comment]
> I think it would make more sense to make that part of the `clap` project rather than @RustCrypto.

I already asked https://github.com/clap-rs/clap/discussions/4122.

**Comment by newpavlov** [comment]
Thank you for the proposal, but I agree with @tarcieri that `clap-digest` is out of scope for RustCrypto.
