### ISSUE TITLE
Sha2 became slower

### ISSUE THREAD

**Issue by tailhook** [RustCrypto/hashes#4]
Hi,

I use sha256 in [vagga](http://github.com/tailhook/vagga) a lot. And I just noticed that current implementation of sha256 is much slower (2x-3x) than old sha2 = 0.1.2.

I do not post benchmarks here because I can't find repository for old code. Do you have a link?

Is there any chance to fix it?

**Comment by newpavlov** [comment]
Thank you for this performance regression report!

Problem was in the `fake-simd` crate, because now it in the separate crate, operations on simd types weren't inlined by compiler. I've added to `fake-simd` inline annotations and it fixed this issue.

**Comment by tailhook** [comment]
Thank you for the quick response! I'm confirming that performance fixed.
