### ISSUE TITLE
sha-1 crate got renamed

### ISSUE THREAD

**Issue by MikailBag** [RustCrypto/hashes#400]
0.10.3: https://docs.rs/sha-1/latest/sha_1/
0.10.0: https://docs.rs/sha-1/0.10.0/sha1/

The package changed name from `sha_1` to `sha`.

Example of failed build: https://github.com/kube-rs/kube-rs/runs/8163260961?check_suite_focus=true

**Comment by MikailBag** [comment]
Since this problem hasn't manifested yesterday, I suspect it may connected to #399

**Comment by newpavlov** [comment]
I will yank it right away.

**Comment by newpavlov** [comment]
BTW, if you can, you should use the `sha1` crate instead of `sha-1`, which is deprecated.

**Comment by Hellzbellz123** [comment]
for anyone that just tried to install something that depends on this you can manually rename the import in "~\.cargo\registry\cache\github.com-1ecc6299db9ec823\[PACKAGE YOUR INSTALLING]" and rerun cargo install [PACKAGE]
