### ISSUE TITLE
sha3: Incorrect type alias for Xof readers?

### ISSUE THREAD

**Issue by andrewwhitehead** [RustCrypto/hashes#426]
In `sha3` 1.10.5 the `Shake256Reader` type alias expands to `XofReaderCoreWrapper<Shake256Core>`, but this produces the following type error when used:

```
the trait bound `Shake256Core: XofReaderCore` is not satisfied
the following other types implement trait `XofReaderCore`:
  CShake128ReaderCore
  CShake256ReaderCore
  Shake128ReaderCore
  Shake256ReaderCore
```

In the `impl_shake` macro this is defined by:

```
pub type $reader_full = XofReaderCoreWrapper<$name>;
```

Which I suspect should be:

```
pub type $reader_full = XofReaderCoreWrapper<$reader>;
```

As a workaround, I am just redefining the type alias as such:

```
type Shake256Reader = sha3::digest::core_api::XofReaderCoreWrapper<sha3::Shake256ReaderCore>;
```

**Comment by newpavlov** [comment]
You are correct, there is a mistake in the impl macro. I will fix it right away.

**Comment by andrewwhitehead** [comment]
Thanks!
