### ISSUE TITLE
reuse the hasher after finalized?

### ISSUE THREAD

**Issue by ibigbug** [RustCrypto/hashes#429]
it seems the `finalize()` will consume the hasher:

> Retrieve result and consume hasher instance.

https://docs.rs/md-5/latest/md5/trait.Digest.html#tymethod.finalize

how ever it doesn't reset the state.

how to reuse and write more data into the hasher after finalized()?

**Comment by tarcieri** [comment]
Use `finalize_reset`

**Comment by ibigbug** [comment]
i think i didn't make it clear - it's not about resetting the state. i.e. continue to write more data after finalize() and finalize() again with more data.

**Comment by tarcieri** [comment]
Then you want to `Clone` prior to finalization

**Comment by burdges** [comment]
Also, merlin was more designed for this sort of thing.  

As an aside, rust maybe needs some `replace_with` method that makes reset methods unnecessary by ensuring zero copies: https://github.com/rust-lang/rfcs/pull/2884#issuecomment-1304576176

**Comment by burdges** [comment]
It appears https://docs.rs/replace_with/ provides equivalent functionality to the `*reset` methods.
