### ISSUE TITLE
[Q&A] Is the SHA1 implementation 'hardened'?

### ISSUE THREAD

**Issue by Byron** [RustCrypto/hashes#431]
I am using this crate over at `gitoxide` for pure Rust builds and this question was ask on [reddit](https://www.reddit.com/r/rust/comments/yo1hb1/comment/ivcmy8b/?utm_source=share&utm_medium=web2x&context=3) recently.

Also I am putting 'hardened' in quotes as I don't know if it's the correct term, but it's used in [the `git` documentation](https://github.com/git/git/blob/master/Documentation/technical/hash-function-transition.txt#L34:L36) accordingly.

Thanks for your help

**Comment by newpavlov** [comment]
No, currently the `sha1` crate does not implement collision detection. See #204.

We are ready to accept a PR which would implement it, but we do not plan to work on it ourselves in the near future.

**Comment by Byron** [comment]
Thanks a lot for letting me know, much appreciated.

I am happy to give it a try, thinking that @pascalkuthe is probably able to do the significant mentoring that this would take 😅.
