### ISSUE TITLE
Add k12

### ISSUE THREAD

**Issue by dhardy** [RustCrypto/hashes#45]
I wrote a KangarooTwelve implementation. It's slow and has horrible code style, but passes the tests at least. Licenced CC0 so feel free to copy.

https://github.com/dhardy/hash-bench/blob/master/src/k12.rs

**Comment by quininer** [comment]
I have some interest in MarsupilamiFourteen.

**Comment by DonaldTsang** [comment]
@quininer nice to see people care about K12 in here

**Comment by oconnor663** [comment]
If anyone working on this wants to benchmark against the [official K12 implementation](https://github.com/XKCP/K12), I have some [very simple Rust bindings](https://github.com/oconnor663/blake2_simd/tree/master/benches/kangarootwelve) that you could copy, which statically link that implementation. The vendored version of that implementation (just updated) does AVX2 and AVX-512 feature detection at runtime.

**Comment by DonaldTsang** [comment]
Okay what about BLAKE3?
