### ISSUE TITLE
Hasher trait not implemented for digests

### ISSUE THREAD

**Issue by PlasmaPower** [RustCrypto/hashes#49]
The `std::hash::Hasher` trait is not implemented for these digests. The trait is identical to the `digest::Input` and `digest::FixedOutput` traits. Implementing it would be useful for me, because I'd like to have my `std::hash::Hash` implementation be usable with a `digest::Digest`.

**Comment by PlasmaPower** [comment]
Oh, I just noticed that the `digest::*Output` traits take `self`, whereas `std::hash::Hasher::finish` takes `&self`. That will be a problem.

**Comment by newpavlov** [comment]
`Hasher` is a really bad fit for crypto hash functions. See for example this [comment](https://github.com/RustCrypto/hashes/issues/29#issuecomment-311869506) and the following discussion.

**Comment by newpavlov** [comment]
One way to circumvent this in your code is to define your generic wrapper type and implement `Hasher` for it:
```Rust
struct MyDigest<D: Digest> {
    d: D
}

impl<D: Digest> Hasher for MyDigest<D> {
    // ..
}
```

**Comment by PlasmaPower** [comment]
I ended up using a similar solution. Perhaps we could add a method to the `digest::Input` trait to accept `std::hash::Hash` objects.

**Comment by newpavlov** [comment]
In that case I will close this issue as we currently don't have plans regarding implementing `Hasher`. Take a look at this [issue](https://github.com/RustCrypto/utils/issues/2), in which we discuss crate for recursively hashing structs. maybe you'll find [mzabaluev/digest-hash](https://github.com/mzabaluev/digest-hash-rs) crate useful.
