### ISSUE TITLE
`sha2` fails to build in Windows on an ARM device

### ISSUE THREAD

**Issue by jdjaustin** [RustCrypto/hashes#502]
`sha2` fails to build in Windows on an ARM device. Removing `asm = ["sha2-asm"]` from `sha2/Cargo.toml` allows the crate to build.

**Comment by tarcieri** [comment]
The `asm` feature is unsupported on MSVC, which is my guess as to what is happening: https://github.com/RustCrypto/asm-hashes/issues/17

We need to migrate to inline ASM, which will fix all of these platform-specific concerns.

**Comment by newpavlov** [comment]
You should find which crate in your dependency tree enables the `asm` feature. We [explicitly state](https://github.com/RustCrypto/hashes/blob/master/sha2/Cargo.toml#L33) that this feature SHOULD NOT be enabled by library crates. The lack of Windows support is a known problem and tracked in the linked asm-hashes issue, so I think we can close this issue in favor of it.
