### ISSUE TITLE
Strange quirk in SHA256 impl

### ISSUE THREAD

**Issue by conradludgate** [RustCrypto/hashes#525]
https://github.com/RustCrypto/hashes/blob/74dcc278daabd787ed9ec30c66616aa729ae6bbc/sha2/src/sha256/soft.rs#L46-L51

The code appears to be doing `rotate_left(x, 7) ^ rotate_left(x, 18) ^ shift_left(x, 3)`, whereas the specification has these flipped:

![Screenshot_2024-01-05-08-25-21-55_3aea4af51f236e4932235fdada7d1643](https://github.com/RustCrypto/hashes/assets/6625462/6e7a99f6-f2fb-49bb-bd31-e9bd33a15b22)

This turns out to be ok because the `shl` and `shr` functions are also flipped:

https://github.com/RustCrypto/hashes/blob/74dcc278daabd787ed9ec30c66616aa729ae6bbc/sha2/src/sha256/soft.rs#L5-L13

So, nothing is broken, just a weird quirk. Should probably be renamed

**Comment by tarcieri** [comment]
The labels for these do appear to be swapped
