### ISSUE TITLE
"no such associated item" in IDE but build succeeds

### ISSUE THREAD

**Issue by alshdavid** [RustCrypto/hashes#529]
In VSCode I am getting this error:
![image](https://github.com/RustCrypto/hashes/assets/12656294/291adb50-a7fe-415f-9837-9a611e36fd96)

```
no such associated itemrust-analyzer[E0599](https://doc.rust-lang.org/stable/error_codes/E0599.html)
sha2
pub type Sha256 = CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, U32, OidSha256>> // size = 112 (0x70), align = 0x8
```
However `cargo build` succeeds without issue.

```
$ uname -a
Linux fedora 6.6.8-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 21 04:01:49 UTC 2023 x86_64 GNU/Linux

$ cargo version
cargo 1.75.0 (1d8b05cdd 2023-11-20)
```

Have I misconfigured something?

**Comment by newpavlov** [comment]
Are you using a Nightly toolchain? Try to update it or switch to stable. If it does not help. then I think it's better to ask in the rust-analyzer repository after looking for similar issues.

**Comment by alshdavid** [comment]
Appears this can be solved for now with this syntax:
```rust
let mut hasher = <Sha256 as Digest>::new();
```
https://github.com/rust-lang/rust-analyzer/issues/15242

**Comment by newpavlov** [comment]
Closing in favor of the rust-analyzer issue. Hopefully, it will be fixed soon.
