### ISSUE TITLE
Link error in SHA2 with asm on macOS

### ISSUE THREAD

**Issue by elliottslaughter** [RustCrypto/hashes#54]
When I compile `sha2` version 0.7.1 with the `asm` feature enabled, I get the following link error:

```
  = note: Undefined symbols for architecture x86_64:
            "_sha512_compress", referenced from:
                sha2_asm::compress512::h2714fa0e6f190002 in libsha2-128ed50e2e0d1cae.rlib(sha2-128ed50e2e0d1cae.sha214.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is on macOS 10.13.4 with Rust 1.26.

To reproduce, run `cargo new --bin test_sha2` and then edit the following files:

`Cargo.toml`:

```
[package]
name = "test_sha2"
version = "0.1.0"

[dependencies]
sha2 = { version = "0.7", features = ["asm"] }
```

`src/main.rs`:

```
extern crate sha2;

use sha2::{Sha512Trunc256, Digest};

fn main() {
    let mut hasher = Sha512Trunc256::new();
    let data = b"Hello world!";
    hasher.input(data);
    // `input` can be called repeatedly
    hasher.input("String data".as_bytes());
    // Note that calling `result()` consumes hasher
    let hash = hasher.result();
    println!("Result: {:x}", hash);
}
```

**Comment by newpavlov** [comment]
Thank you for reporting this!

It seems there is a problem with [`sha2-asm`](https://github.com/RustCrypto/asm-hashes/tree/master/sha2) build script. Unfortunately I currently don't have macOS to work on it, so I hope someone will help with it.

**Comment by elliottslaughter** [comment]
Please see https://github.com/RustCrypto/asm-hashes/pull/4 for a fix.

**Comment by newpavlov** [comment]
I've published updates to crates.io, so `cargo update` should solve the problem.

**Comment by elliottslaughter** [comment]
Fix is confirmed in the original application on sha2-asm 0.5.1. Thanks!
