### ISSUE TITLE
Sha256::new() is always marked as an error in the vscode

### ISSUE THREAD

**Issue by nachocodexx** [RustCrypto/hashes#548]
Hi, I have the following problem: 
![Untitled](https://github.com/RustCrypto/hashes/assets/16262414/a29ee6f2-6c0c-41ce-b573-f3c5d91dc435)

I don't know where to find help with this problem, maybe it is not related to this crate because the program works and compile, but this Sha256::new() is always marked as an error.

**Comment by newpavlov** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/15242
