### ISSUE TITLE
MD5 performance optimization

### ISSUE THREAD

**Issue by raphaelcohn** [RustCrypto/hashes#57]
In line 53 in `lib.rs`, the function `hash()` initialized the output array as `[0; 16]`.

I believe this can be optimized to `unsafe { ::std::mem::uninitialized()` }, as all the bytes in the output array are overwritten.

When computing many hashes per second in an environment where hash result matters (eg authenticating TCP segments with the MD5 signature option), this is just another little win.

**Comment by tarcieri** [comment]
Have you compared the output assembly for these two cases (in e.g. [godbolt](https://godbolt.org/)) or benchcmping the change? Just curious if it's actually a win. I think it's nice to have tangible justifications for use of `unsafe`.

**Comment by newpavlov** [comment]
Usually compiler (read LLVM) is smart enough to recognize that zeroing is unnecessary in such simple cases.  See this [assembly](https://godbolt.org/g/SWwCiY). So the proposed `unsafe` is not required for the optimal performance.
