### ISSUE TITLE
Finalising a sha256 has into an [u8; 32]

### ISSUE THREAD

**Issue by WhyNotHugo** [RustCrypto/hashes#572]
I'm trying to generate the sha256 for some data into a `[u8; 32]`. I currently have [some code that hashes my data into a string](https://git.sr.ht/~whynothugo/vdirsyncer-rs/tree/4e960843/item/vstorage/src/util.rs#L22-41) (e.g.: a hex representation of the hash):

```rust
pub(crate) fn hash(raw_data: impl AsRef<str>) -> String {
    let mut hasher = Sha256::new();

    // ...
    hasher.update(some_data);
    hasher.update(some_data);
    // ...

    format!("{:X}", hasher.finalize())
}
```

I'd like for this to return a `[u8;8]` instead, but I'm having a really hard time understanding what's going on beneath so many layers of abstractions. `Sha256::new()` returns a `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>, OidSha256>>`. It's not very clear to me what `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>, OidSha256>>` is or or how I'm supposed to reason about it beyond the basic examples in the README. The documentation for `CoreWrapper` points to [`block_buffer::BlockBuffer`](https://docs.rs/block-buffer/0.10.4/block_buffer/struct.BlockBuffer.html), but that seems to be something used when _implementing_ a hash function, not when using one.

`CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>, OidSha256>>` implements `Digest`, which has a [`finalize_into`](https://docs.rs/sha2/0.10.8/sha2/trait.Digest.html#tymethod.finalize_into) method, but that expects an un-exported type as input, so it doesn't seem to be what I'm looking for.

Is there any way to write the digest directly into a `[u8;32]`?

**Comment by newpavlov** [comment]
`finalize` for SHA-256 returns [`GenericArray<u8; U32>`](https://docs.rs/generic-array/latest/generic_array/struct.GenericArray.html) (you can not click on type in the `digest` docs because of a certain rustdoc bug) which effectively is `[u8; 32]`. It implements `Into<[u8; 32]>` trait, so you can write `let hash: [u8; 32] = hasher.finalize().into();`. Now, if you want to return only 8 bytes, you have to decide which bytes to take and which to discard. `GenericArray` supports all the usual slice operations, so it should be easy to do.

**Comment by tarcieri** [comment]
@WhyNotHugo regarding the diagnostics, here's a tracking issue for that: https://github.com/RustCrypto/traits/issues/1069

**Comment by WhyNotHugo** [comment]
Er, sorry, I meant `[u8;32]`, my bad.

**Comment by WhyNotHugo** [comment]
`let hash: [u8; 32] = hasher.finalize().into();` would generate a [`GenericArray<u8; U32>`](https://docs.rs/generic-array/latest/generic_array/struct.GenericArray.html) and then convert that into an array. Is there some way to get the hash directly without the intermediate type?

**Comment by tarcieri** [comment]
You should be able to do something like:

```rust
let mut buf = [0u8; 32];
digest.finalize_into(buf.as_ref());
```

(it might require `.as_ref().into()`)

However note that there's no cost to the "intermediate type" and these two are really equivalent.

**Comment by WhyNotHugo** [comment]
Thanks, `let hash: [u8; 32] = hasher.finalize().into();` works fine.

I prefer to avoid adding generic-array as a direct dependency and using `GenericArray` directly since I don't want internal implementation details of `sha2` leaking into my own codebase.

**Comment by WhyNotHugo** [comment]
> However note that there's no cost to the "intermediate type" and these two are really equivalent.

This is a good-to-know. Do you think it's worth including the example above in the README or in the docs?

**Comment by newpavlov** [comment]
We are in the process of migrating to [`hybrid-array`](https://docs.rs/hybrid-array), which will make extraction of array easier, so it's probably not worth to write new `GenericArray`-centric docs now.

**Comment by WhyNotHugo** [comment]
Nice, happy to see that there is also a path to move onto const-generic, that will definitely make things simpler on the API side :)
