### ISSUE TITLE
Key stretching to 64B.

### ISSUE THREAD

**Issue by dpc** [RustCrypto/hashes#58]
Hi,

I need to use blake2 for key stretching to a 64B value. Is VariableOutput the way to go or am I misunderstanding its purpose? Is effectively making me use BLAKE-512?

Thank you for your help!

**Comment by newpavlov** [comment]
`VariableOutput` in case of BLAKE2s can be used to produce hashes with sizes up to 32 bytes. Per specification it essentially just uses slightly different initialization and truncates output. So for 64 bytes you'll have to use BLAKE2b, [KDF](https://github.com/RustCrypto/KDFs), or hash which implements [`ExtendableOutput`](https://docs.rs/digest/0.7.5/digest/trait.ExtendableOutput.html) (only `sha3` for now).

**Comment by dpc** [comment]
Thank you!
