### ISSUE TITLE
Use big endian for streebog and gost94

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/hashes#59]
GOSTs are specified in terms of N-bit integers and do not define byte order which should be used. Initially I've chose to use little endian order, but probably big endian would have been a better choice. This will allow to simplify code a bit, and will probably be more compatible with other implementations.

TODO: Look into other implementations.

**Comment by tarcieri** [comment]
@newpavlov I think we can close this?

**Comment by newpavlov** [comment]
Yes, interestingly enough the current implementation passes test vectors from https://github.com/gost-engine/engine, so I guess it was implemented correctly...
