### ISSUE TITLE
Technically Keccak ≠ SHA-3

### ISSUE THREAD

**Issue by Ma124** [RustCrypto/hashes#60]
SHA-3 is just based on Keccak because it uses a slightly different padding function.

Maybe this should be corrected in the README but of course it's entirely your decision because the difference isn't that big.

**Comment by tarcieri** [comment]
Keccak is the sponge function at the core of the entire SHA-3 family, including the SHA-3 digest function itself and the SHAKE XOFs.

Is this issue regarding Keccak being in the "Alt name" column for SHA-3?

**Comment by Ma124** [comment]
Yes that's what I mean Keccak isn't another name for SHA-3 but rather a very similar hash function.

**Comment by tarcieri** [comment]
Keccak isn't a hash function, it's a sponge function. You can build many different cryptographic primitives on top of it, from hash functions (see also TupleHash) to XOFs (SHAKE) to MACs (KMAC) to PRFs (Kravatte) to authenticated encryption (Keyak).

**Comment by newpavlov** [comment]
Are you talking about readme or about `Keccak224`, `Keccak256`, etc. implementations in the `sha3` crate? If it's about former, then citing Keccak [paper](https://keccak.team/obsolete/Keccak-main-1.0.pdf):
>Keccak is  a  family  of  cryptographic  hash  functions  or,  more  accurately,  sponge functions.   This  document  describes  the  properties  of  the Keccak family  and  presents its members as candidates to NIST’s request for a new cryptographic hash algorithm family called SHA-3.

So you are right, it's not ≠ realtion, but SHA-3 is rather a subset of Keccak primitives family, so I think it's reasonable to use it as an alt name.
