### ISSUE TITLE
Release 0.10.8 Sha256 issue

### ISSUE THREAD

**Issue by OlekRia** [RustCrypto/hashes#611]
`use sha2::{Digest, Sha256};

Sha256::new()
`

Made as in documentation described.
Raises a error: method new() doesn't exist.

It works well on 0.9 version.

P.S. Macbook Pro M2

**Comment by newpavlov** [comment]
It [works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1f24d7d5d052408332d0274986922350) without issues (the playground uses `sha2 v0.10.8`). Also, we test our code examples as part of CI, so the problem is likely with your code or setup.
