### ISSUE TITLE
Package for sha2 contains binary tests

### ISSUE THREAD

**Issue by Yoric** [RustCrypto/hashes#62]
Tested with 0.7.1 (I cannot test with 0.8.0 atm).

  - sha2/tests/data/sha224/test1.output.bin
 - sha2/tests/data/sha224/test2.output.bin
 - sha2/tests/data/sha224/test3.output.bin
 - sha2/tests/data/sha256/one_million_a.output.bin
 - sha2/tests/data/sha256/test1.output.bin
 - sha2/tests/data/sha256/test2.output.bin
 - sha2/tests/data/sha256/test3.output.bin
 - sha2/tests/data/sha384/test1.output.bin
 - sha2/tests/data/sha384/test2.output.bin
 - sha2/tests/data/sha384/test3.output.bin
 - sha2/tests/data/sha512/test1.output.bin
 - sha2/tests/data/sha512/test2.output.bin
 - sha2/tests/data/sha512/test3.output.bin
 - sha2/tests/data/sha512_224/test1.output.bin
 - sha2/tests/data/sha512_224/test3.output.bin
 - sha2/tests/data/sha512_256/test1.output.bin

I assume that this is an error. At least, it gets flagged as "odd" by the Firefox submission mechanism.

**Comment by newpavlov** [comment]
No, it's intended. Those files are test vectors in binary format (to save space and bandwidth a bit), which are packaged together with the main code. This is useful for example for [`crater`](https://github.com/rust-lang-nursery/crater) to check if new Rust versions don't have any regressions. In the v0.8.0 those files are replaced with "packed" format with `blb` extension, hope they will not be flagged by the Firefox submission mechanism.

**Comment by Yoric** [comment]
Ok, good to know. For what it's worth, with 0.7.1, the Firefox submission mechanism kind of chokes on these tests. Pretty sure it's a bug on the Firefox tooling side, of course.
