### ISSUE TITLE
soft-sha256 error on esp32c3

### ISSUE THREAD

**Issue by Algorab** [RustCrypto/hashes#629]
On my embedded project the esp32c3 produce errors:
with default feature:
`E (14969) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (14969) task_wdt:  - IDLE (CPU 0)
E (14969) task_wdt: Tasks currently running:
E (14969) task_wdt: CPU 0: main
E (14969) task_wdt: Print CPU 0 (current core) backtrace
Print CPU 0 (current core) registers
Core  0 register dump:
MEPC    : 0x40000358  RA      : 0x4200709a  SP      : 0x3fc9ae80  GP      : 0x3fc91000  
0x4200709a - <sha2::core_api::Sha256VarCore as digest::core_api::VariableOutputCore>::finalize_variable_core
    at ??:??
0x3fc91000 - __global_pointer$
    at ??:??
TP      : 0x3fc507f0  T0      : 0xf5ee36b0  T1      : 0x400005e0  T2      : 0x32087353  
S0/FP   : 0x0000000c  S1      : 0x0000ff00  A0      : 0x3fc9ae98  A1      : 0x3fc9aeb0  
A2      : 0x00000004  A3      : 0x00000004  A4      : 0x00000004  A5      : 0x3fc9ae98  
A6      : 0x6f19895f  A7      : 0x66100201  S2      : 0x3fc9af44  S3      : 0x3c10435c  
0x3c10435c - $d.52
    at ??:??
S4      : 0x3fcaa5b8  S5      : 0x3fc9b130  S6      : 0x00000000  S7      : 0x01000000  
S8      : 0x3fc9afa0  S9      : 0x3fc9afc0  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0xed8a3178  T4      : 0xe6700b0b  T5      : 0x7e9656c5  T6      : 0xd6914bd2  
MSTATUS : 0x00000012  MTVEC   : 0x00000020  MCAUSE  : 0x00000011  MTVAL   : 0xe7ac0bee  
MHARTID : 0xc41428fd  
`

with feature std:
`E (15518) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (15518) task_wdt:  - IDLE (CPU 0)
E (15518) task_wdt: Tasks currently running:
E (15518) task_wdt: CPU 0: main
E (15518) task_wdt: Print CPU 0 (current core) backtrace
Print CPU 0 (current core) registers
Core  0 register dump:
MEPC    : 0x4202819e  RA      : 0x420276ee  SP      : 0x3fc9ab00  GP      : 0x3fc91000  
0x4202819e - sha2::sha256::soft::shl
    at /Users/stl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sha2-0.10.8/src/sha256/soft.rs:7
0x420276ee - sha2::sha256::soft::sha256_digest_block_u32
    at /Users/stl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sha2-0.10.8/src/sha256/soft.rs:159
0x3fc91000 - __global_pointer$
    at ??:??
TP      : 0x3fc507f0  T0      : 0xdcc7dbd3  T1      : 0x567331d5  T2      : 0x284b28c2  
S0/FP   : 0x1fc9807d  S1      : 0x1fc98000  A0      : 0x3fc9ae1c  A1      : 0x3fc9ae2c  
A2      : 0x18450000  A3      : 0x3fc9acf0  A4      : 0x3fc9ad04  A5      : 0x0000159c  
A6      : 0x25946114  A7      : 0x01f47f26  S2      : 0x18450965  S3      : 0xcc75559c  
S4      : 0x0c7dbd3d  S5      : 0x04b28c22  S6      : 0x0ace663a  S7      : 0x5ca3469c  
S8      : 0x59bab531  S9      : 0x09ca1855  S10     : 0xe027f2d7  S11     : 0x73137773  
T3      : 0xaaace663  T4      : 0x4c03e8fe  T5      : 0x63ede9ee  T6      : 0x7a7b98fb  
MSTATUS : 0x0d0d8b5c  MTVEC   : 0x2000751a  MCAUSE  : 0x2f787702  MTVAL   : 0x7d166023  
MHARTID : 0x63ede9ee  
`

maybe the dumps help to fix.

The esp is running on ESP IDF

**Comment by newpavlov** [comment]
It looks like the hash computation simply takes too long. Try either configuring your watchdog differently, or split hashed message into smaller chunk and yield between each chunk.

**Comment by Algorab** [comment]
Thanks for pointing me in the right direction. After increasing the timings much more than I expected, now it is working.
