### ISSUE TITLE
Incorrect return for sha1 for no data

### ISSUE THREAD

**Issue by ported-pw** [RustCrypto/hashes#633]
If 0 bytes of data are passed to SHA1, it currently returns a zero-initialized buffer.
It should return `da39a3ee5e6b4b0d3255bfef95601890afd80709`.

**Comment by newpavlov** [comment]
You haven't provided any code... This snippet returns the expected result:
```rust
use sha1::{Sha1, Digest};
let h = Sha1::new().finalize();
println!("{h:x}");
```

**Comment by ported-pw** [comment]
Very sorry to have wasted your time - my code is so dead simple, and I looked a bit through the test cases here, that I thought it couldn't be any other way. I just looked at the wrong spot, the service whose hashes I was comparing with is doing the wrong thing and I had accidentally swapped the params in the log message 🤦 .
Again, apologies for wasting your time.
