### ISSUE TITLE
How can I save the hash value to file

### ISSUE THREAD

**Issue by xxks-kkk** [RustCrypto/hashes#71]
Hello,

I was wondering how can I save the hash value into a file. For example, I want to save `hash` to the file `checksum_filename` (see below). Thanks!

```rust
    let checksum_filename = "checksum_origin.txt";
    let mut hasher = Sha256::new();
    let mut file = fs::File::open(filename)?;
    let n = io::copy(&mut file, &mut hasher)?;
    let hash = hasher.result();
    let mut output = fs::File::create(checksum_filename)?;
    println!("Hash value: {:x}", hash);
```

**Comment by newpavlov** [comment]
If you want to write checksum in hex format, you can use [`write!`](https://doc.rust-lang.org/std/macro.write.html) macro, i.e. in the last line instead of `println!` you will write `write!(&mut output, "Hash value: {:x}", hash)`.

**Comment by xxks-kkk** [comment]
Thanks!
