### ISSUE TITLE
Add support for Persona and Salt to Blake2

### ISSUE THREAD

**Issue by dignifiedquire** [RustCrypto/hashes#75]
I would like to add these, based on this PR: https://github.com/cesarb/blake2-rfc/pull/9 but the current traits for `Digest` don't really allow for something that has custom parameters. 

@newpavlov  My question is, should something like `with_params` be added to an existing trait, should this be a new trait, be just a one off thing for Blake, or am I missing something.

**Comment by newpavlov** [comment]
I think it should be an inherent method for `blake2` types and I will gladly accept a PR with such addition. BTW we already have semi-private [`with_parameter_block`](https://github.com/RustCrypto/hashes/blob/master/blake2/src/blake2.rs#L112) method which can be used to implement `with_params` method like in the linked PR.
