### ISSUE TITLE
SHA2 does not compile when targeting android with the asm feature

### ISSUE THREAD

**Issue by dignifiedquire** [RustCrypto/hashes#76]
Error log can be seen here: https://gist.github.com/r10s/a29b59bcd05e3d62b8eb5d9b6273ddd7 it looks like a bunch of instructions that are not available for `armv7-linux-androideabi`

**Comment by newpavlov** [comment]
`sha2-asm` currently only [supports](https://docs.rs/sha2-asm/0.5.1/sha2_asm/) x86 and x86-64. We have [plans](https://github.com/RustCrypto/asm-hashes/issues/5) for using OpenSSL assembly which could add support for ARM targets, but we are not there yet.

**Comment by dignifiedquire** [comment]
I see, what do you think of adding some `cfg`s to disable the asm feature when building against other targets?

**Comment by newpavlov** [comment]
Yes, I should've added such cfgs. Fixed in RustCrypto/asm-hashes#6.

**Comment by dignifiedquire** [comment]
Thank you
