### ISSUE TITLE
sha-1 is not minimal-versions correct

### ISSUE THREAD

**Issue by CAD97** [RustCrypto/hashes#79]
Due to [block-buffer:0.7.0 not being minimal-versions correct](https://github.com/RustCrypto/utils/pull/23).

Noticed in https://github.com/pest-parser/pest/pull/390.

**Comment by CAD97** [comment]
This will apply to any crate that specifies `block-buffer="0.7"` rather than `block-buffer="0.7.3"` (unless `block-buffer:0.7.0` is yanked).

**Comment by newpavlov** [comment]
I've yanked v0.7.0, as I think it will be the simplest fix of this issue for `sha-1` and other crates. Can you check if issues is fixed?

**Comment by CAD97** [comment]
Yep, it's good now: https://github.com/pest-parser/pest/pull/391
