### ISSUE TITLE
Output size

### ISSUE THREAD

**Issue by NN-Binary** [RustCrypto/hashes#84]
Hi,

i'd like to get the original output size (U32;8) from the SHA256 instead of U8;32
How can I do it?

Thanks

**Comment by newpavlov** [comment]
Use [`byteorder`](http://docs.rs/byteorder/) crate. For example:
```rust
use byteorder::{LE, ByteOrder};
let mut buf = [0u32; 8];
LE::read_u32_into(&hash_value, &mut buf);
```

**Comment by NN-Binary** [comment]
Thanks for the help! :)

That make a useless operation right? I was thinking that the original output of sha is 32;8, could'nt we avoid this operation?

**Comment by newpavlov** [comment]
SHA-256 indeed uses `[u32; 8]` internally, but it's nothing more than implementation detail. Assuming a proper alignment (which is present in this case) converting `[u8; 32]` to `[u32; 8]` using little-endian encoding on little-endian machine will be optimized out.

**Comment by NN-Binary** [comment]
Do you think you could provide natively an option to export with U32;8 and U64;4 ?

**Comment by newpavlov** [comment]
No, for the same reason why crates do not provide hex output: separation of concerns. SHA-256 outputs 256 bits and it's for you to decide how to interpret them as an array of u32's, e.g. you can use big, little or native-endian encoding.

**Comment by NN-Binary** [comment]
But from what I read, you are already doing that natively (aka converting from U32;8 to U8;32)  so You are already taking this freedom right?

How do I output the native content (U32;8) in the crate? (without double transmute)

**Comment by newpavlov** [comment]
Again, it's nothing more than implementation detail. Algorithm outputs 256 bits. Period. FWIW behind `Sha256` type you may have code which uses hardware acceleration and does not use any `u32`s.

You have rather strange fixation on "native" (though I don't follow what exactly you mean by it). if you'll take a look at implementation, you'll see that it [uses](https://github.com/RustCrypto/hashes/blob/master/sha2/src/sha256.rs#L98) `byteorder` and on little-endian machines we have to swap bytes to get a correct result.

**Comment by NN-Binary** [comment]
Pardon my fixation :D I'm just trying to understand performance wise.
In your code here, I read:

` BE::write_u32_into(&self.engine.state.h, out.as_mut_slice());`
Does this have an overhead? write_u32_into has a cost (I think?) that could be avoided for people that do not want to have this cost, especially if you actually want to use it as u32;8 (example Insert it "as is" in a DB)

**Comment by newpavlov** [comment]
On x86-64 it results in 8 `bswapl` instructions, assuming 0.5 throughput it will take 4 cycles, i.e. on 4 GHz CPU it will take only 1 ns! Assuming functions will get inlined (e.g. with `lto=true`) it's highly likely that two `bswapl` will be optimized out. And do not forget that you pay this cost only once per hash computation!

If you are looking for performance improvements, there are much-much-much more productive areas to look into.

**Comment by NN-Binary** [comment]
Oh, didn't realize it was that cheap :)

Thanks for the clarifications, you've been super helpful
