### ISSUE TITLE
Add `fixed_result_into` to prevent copy

### ISSUE THREAD

**Issue by bwesterb** [RustCrypto/hashes#86]
Rust does [not](https://github.com/rust-lang/rust/issues/32966) ([yet](https://github.com/rust-lang/rust/pull/47954)) implement named return value optimisation, so `fixed_result` forces a copy.

How would you feel about adding a

```rust
fn fixed_result_into(mut self, out : &mut GenericArray<u8, Self::OutputSize>)
```

function to the `FixedOutput` trait so that the copy can be avoided.  I'm happy to create a PR.

(Background: I'm implementing the hash-based signature XMSSMT in rust, where lots of hashes are computed on on very short inputs.  These copies have a significant overhead.)

**Comment by tarcieri** [comment]
It seems like with const generics on the horizon there should (possibly) be a way to do this in terms of `FromIterator` soon? e.g.

https://internals.rust-lang.org/t/collecting-iterators-into-arrays/10330

**Comment by newpavlov** [comment]
I was thinking about doing the following re-design in the next `digest` version:
```rust
pub trait FixedOutput {
    type OutputSize: ArrayLength<u8>;

    /// Private method not intended to be used directly
    fn _fixed_result_core(&mut self, out: &mut GenericArray<u8, Self::OutputSize>, reset: bool);

    #[inline]
    fn fixed_result(self) -> GenericArray<u8, Self::OutputSize> {
        let mut buf = Default::default();
        self._fixed_result_core(&mut buf, false);
        buf
    }

    #[inline]
    fn fixed_result_reset(&mut self) -> GenericArray<u8, Self::OutputSize> { .. }
    fn fixed_result_into(self, out: &mut GenericArray<u8, Self::OutputSize>) { .. }
    fn fixed_result_into_reset(&mut self, out: &mut GenericArray<u8, Self::OutputSize>) { .. }
}
```
I think `#[inline]` should help with needless copies.
