### ISSUE TITLE
HMAC-SHA1

### ISSUE THREAD

**Issue by rendaw** [RustCrypto/hashes#93]
Hello, thanks for this awesome project.

Doing some OpenID 2 stuff, and for full compatibility it needs to support HMAC SHA-1.  It appears that none of the digest traits are implemented for SHA1.  Would this be possible to add, and are there any significant technical barriers to it?

**Comment by tarcieri** [comment]
Are you sure you're looking at the right crate? Note that as the `sha1` crate name was already taken, the name of the compatible crate is `sha-1`, which implements the `BlockInput` and `FixedOutput` traits from `digest` v0.8:

https://docs.rs/sha-1/0.8.1/sha1/struct.Sha1.html

**Comment by rendaw** [comment]
You're absolutely right, that was it :man_facepalming: 

Sorry for the noise!

**Comment by tarcieri** [comment]
No worries, it's a little bit confusing. Fortunately it only impacts `md-5` and `sha-1`
